server:
  port: 9092
  
spring:
  application:
    name: Communication-Service

eureka:
  instance:
    prefer-ip-address:  true
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka